<?php foreach ($this->v['commits'] as $day => $_commits): ?>
    <tr>
        <td colspan="4"><h5 class="text-danger"><b><?= $day ?></b></h5></td>
    </tr>
    <?php foreach ($_commits as $commit): ?>
        <tr>
            <td>
                <a href="<?= $this->v['prefix'] ?><?= isset($this->v['blob']) ? 'blob' : 'commit' ?>/<?= $commit['hash'] ?><?= isset($this->v['path']) ? '/' . $this->v['path'] : '' ?>"><?= substr($commit['hash'],
                        0,
                        8) ?></a></td>
            <td><?= $commit['msg'] ?></td>
            <td><?= date('Y/m/d H:i', $commit['time']) ?></td>
            <td><?= $commit['author'] ?></td>
        </tr>
    <?php endforeach ?>
<?php endforeach ?>