<ul class="list-unstyled">
    <?php foreach ($this->v['diffs'] as $key => $file): ?>
        <li>
            <?php if($key > 20):?>
                由于更新的文件过多，此处只显示前20个文件...
                <?php
                break;
            endif?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h5><em class="glyphicon glyphicon-file"></em><?= $file['to']['path'] ?></h5>
                </div>
                <div class="panel-body">
                    <?php if ($file['type'] == 'file'): ?>
                        <table class="diffs">
                            <?php foreach ($file['blocks'] as $blocks): ?>
                                <?php foreach ($blocks as $key => $block): ?>
                                    <?php if ($key == 0): ?>
                                        <tr class="block block-start">
                                            <td class="line-from">...</td>
                                            <td class="line-to">...</td>
                                            <td class="code"><?= htmlentities($block['line']) ?></td>
                                        </tr>
                                    <?php else:
                                        $className = 'block';
                                        if (isset($block['to']) || isset($block['from'])) {
                                            if (!isset($block['to'])) {
                                                $className .= ' block-from';
                                            } else {
                                                if (!isset($block['from'])) {
                                                    $className .= ' block-to';
                                                }
                                            }
                                        } else {
                                            $className .= ' block-end';
                                        }
                                        ?>
                                        <tr class="<?= $className ?>">
                                            <td class="line-from"><?= (isset($block['from']) ? $block['from'] : '&nbsp;') ?></td>
                                            <td class="line-to"><?= (isset($block['to']) ? $block['to'] : '&nbsp;') ?></td>
                                            <td class="code"><?= str_replace(' ', '&nbsp;',
                                                    htmlentities($block['line'])) ?></td>
                                        </tr>
                                    <?php endif ?>
                                <?php endforeach ?>
                            <?php endforeach ?>
                        </table>
                    <?php elseif ($file['type'] == 'bin'): ?>
                        <?php
                        $ext = strtolower(pathinfo($file['to']['path'], PATHINFO_EXTENSION));
                        switch ($ext) {
                            case 'jpg':
                            case 'png':
                            case 'gif':
                                echo '<img data-original="' . $this->v['prefix'] . 'raw/' . $this->v['git']['branch'] . $file['to']['path'] . '"/>';
                                break;
                        }
                        ?>
                    <?php endif ?>
                </div>
            </div>

        </li>
    <?php endforeach ?>
</ul>