<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>Git项目主页</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/static/highlightjs/styles/github.css" rel="stylesheet"/>
    <script src="/static/jquery/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/highlightjs/highlight.pack.min.js"></script>
</head>
<body>
<?php
$prefix = '/' . $this->v['git']['group'] . '/' . $this->v['git']['name'] . '/';
$branch = $this->v['git']['branch'];
$navType = isset($this->v['navType']) ? $this->v['navType'] : 'home';
$this->set('prefix', $prefix);
?>
<div class="container">
    <h1>
        <?= $this->v['git']['group'] ?>/<?= $this->v['git']['name'] ?>
        <small><?= $this->v['git']['url'] ?></small>
    </h1>

    <ul class="nav nav-tabs">
        <li role="presentation"<?=($navType == 'home' ? ' class="active"' : '')?>><a href="<?= $prefix ?>">首页</a></li>
        <li role="presentation"<?=($navType == 'commit' ? ' class="active"' : '')?>><a href="<?= $prefix ?>commits/<?= $branch ?>">提交</a></li>
        <li role="presentation"<?=($navType == 'branch' ? ' class="active"' : '')?>><a href="<?= $prefix ?>branches">分支</a></li>
    </ul>
    <?php if (isset($this->v['branches']) && count($this->v['branches']) > 1):?>
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="true">
            <?= $branch ?>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <?php foreach ($this->v['branches'] as $branch): ?>
                <li><a href="<?= $prefix ?>tree/<?= $branch['name'] ?>"><?= $branch['name'] ?></a></li>
            <?php endforeach ?>
        </ul>
    </div>
    <?php endif?>

    <?=$this->getContent()?>
</div>
<script>
    $('pre code').each(function(i, block) {
        hljs.highlightBlock(block);
    });
</script>
</body>
</html>