<?// print_r($this->v['blame']);?>
<?php include __DIR__.'/menu.phtml'?>
<ul class="list-unstyled">
    <li>
        <div class="panel panel-default">
            <div class="panel-body">
               <pre>  <table>
                    <?php foreach($this->v['blame'] as $blame_key=>$blame_val){?>
                        <tr class="block block-start">
                            <td class="code"><?= str_replace(' ', '&nbsp;',
                                    htmlentities($blame_val)) ?></td>
                        </tr>
                    <?php }?>
                </table></pre>
            </div>
        </div>
    </li>
</ul>
