<?php include __DIR__.'/menu.phtml'?>
<ul class="list-unstyled">
        <li>
            <div class="panel panel-default">

                <div class="panel-body">
                        <table class="diffs">
                            <?php foreach ($this->v['blame']['blocks'] as $blocks): ?>
                                <?php foreach ($blocks as $key => $block): ?>
                                    <?php if ($key == 0): ?>

                                    <?php else:?>
                                        <tr class="block">
                                            <td ><?= date('Y-m-d H:i:s', $block['time']) ?></td>
                                            <td ><?= $block['author'] ?></td>
                                            <td class="code"><?= str_replace(' ', '&nbsp;',
                                                    htmlentities($block['line'])) ?></td>
                                        </tr>
                                    <?php endif ?>
                                <?php endforeach ?>
                            <?php endforeach ?>
                        </table>
                </div>
            </div>

        </li>
</ul>
