<?php include __DIR__.'/menu.phtml'?>
<ul class="list-unstyled">
        <li>
            <div class="panel panel-default">

                <div class="panel-body">
                        <table class="diffs">
                            <?php foreach ($this->v['blame'] as $block): ?>
                                        <tr class="block">
<!--                                            <td >--><?//= $block['msg'] ?><!--</td>-->
                                            <td ><?= $block['author'] ?></td>
                                            <td class="line-to"><?= $block['line'] ?></td>
                                            <td class="code"><?= str_replace(' ', '&nbsp;',
                                                    htmlentities($block['code'])) ?></td>
                                        </tr>
                            <?php endforeach ?>
                        </table>
                </div>
            </div>

        </li>
</ul>
