<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>Git项目主页</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<?php
$prefix = '/' . $this->v['git']['group'] . '/' . $this->v['git']['name'] . '/';
$branch = $this->v['git']['branch'];
?>
<div class="container">
    <h1><?= $this->v['git']['group'] ?>/<?= $this->v['git']['name'] ?></h1>
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="<?= $prefix ?>commits/<?= $branch ?>">提交</a></li>
        <li role="presentation" class="active"><a href="<?= $prefix ?>branches">分支</a></li>
    </ul>

    <table class="table table-striped">
        <?php foreach ($this->v['branches'] as $branch): ?>
            <tr>
                <td><a href="<?=$prefix?>/branch/<?=$branch['name']?>"><?= $branch['name'] ?></a></td>
                <td><?=$branch['hash']?></td>
                <td><?=$branch['msg']?></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>
</body>
</html>