<h2><?= $this->v['commit']['msg'] ?></h2>
<label class="label label-info">作者</label><span><?= $this->v['commit']['author'] ?></span>
<br/>
<label class="label label-info">时间</label><span><?= date('Y/m/d H:i:s', $this->v['commit']['time']) ?></span>
<hr/>
<div class="row">
    <div class="col-md-8">
        有<?= count($this->v['commit']['files']) ?>个文件收到影响，<span class="text-success">增加了<?= $this->v['commit']['add'] ?>
            行</span>，<span class="text-danger">删除了<?= $this->v['commit']['delete'] ?>行</span>。
    </div>
    <div class="col-md-4">

    </div>
</div>

<?php include __DIR__.'/components/diffs.phtml'?>