<?php if (!$this->v['isAjax']): ?>
<table class="table table-striped table-responsive" id="commitList">
    <?php endif ?>

    <?php include __DIR__.'/components/commits.phtml'?>

    <?php if (!$this->v['isAjax']): ?>
</table>
<?php if ($this->v['nextHash']): ?>
    <div class="text-center">
        <a id="nextCommitLink" data-hook="ajaxable" data-hook-option="{
            container: '#commitList>tbody'
        }" href="<?=$this->v['prefix']?>commits/<?= $this->v['nextHash'] ?>" class="btn btn-lg btn-primary">下一页..</a>
    </div>
<?php endif ?>
<?php else: ?>
    <script>
        <?php if($this->v['nextHash']):?>
        $('#nextCommitLink').attr('href', '<?=$this->v['prefix']?>commits/<?=$this->v['nextHash']?>');
        <?php else:?>
        $('#nextCommitLink').hide();
        <?php endif?>
    </script>
<?php endif?>
