<table class="table table-striped">
    <thead>
    <tr>
        <th colspan="3">
            文件列表
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
    $pDir = dirname($this->v['git']['path']);
    if ($pDir):?>
        <tr>
            <td><a href="<?= $this->v['prefix'] ?>tree/<?= $this->v['git']['branch'] ?>/<?= $pDir ?>">..</a></td>
            <td></td>
            <td></td>
        </tr>
    <?php endif ?>
    <?php foreach ($this->v['nodes']['dirs'] as $node): ?>
        <tr>
            <td>
                <em class="glyphicon glyphicon-folder-close text-primary"></em>
                <a href="<?= $this->v['prefix'] ?>tree/<?= $this->v['git']['branch'] ?>/<?= $node['path'] ?>"><?= $node['name'] ?></a>
            </td>
            <td></td>
            <td></td>
        </tr>
    <?php endforeach ?>
    <?php foreach ($this->v['nodes']['files'] as $node): ?>
        <tr>
            <td>
                <em class="glyphicon glyphicon-file text-success"></em>
                <a href="<?= $this->v['prefix'] ?>blob/<?= $this->v['git']['branch'] ?>/<?= $node['path'] ?>"><?= $node['name'] ?></a>
            </td>
            <td></td>
            <td><?= $node['size'] ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>