<h2><?=$this->v['merge']['title']?></h2>

<ul class="nav nav-tabs" id="compareNav">
    <li class="active"><a href="#reviewList">评审</a></li>
    <li><a href="#commitList">提交</a></li>
    <li><a href="#diffList">变化</a></li>
</ul>

<div id="reviewList" class="navList">
    <form id="formMerge"
          class="form-horizontal"
          method="get"
          action="<?= $this->v['prefix'] ?>_handle_merge"
    >
        <div class="form-group">
            <label class="col-sm-1 control-label">申请时间</label>
            <div class="col-sm-8">
                <?=date('Y/m/d H:i:s', $this->v['merge']['create_time'])?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label">来源分支</label>
            <div class="col-sm-8">
                <code><?=$this->v['orig']?></code>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label">目标分支</label>
            <div class="col-sm-8">
                <code><?=$this->v['dest']?></code>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label">是否通过</label>
            <div class="col-sm-8">
                <input type="radio" value="2"/> 通过
                <input type="radio" value="4"/> 拒绝
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label">评论</label>
            <div class="col-sm-4">
                <textarea name="remark" class="form-control" rows="4"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-1">
                <input type="submit" value="确定" class="btn btn-lg btn-primary"/>
            </div>
        </div>
    </form>
</div>

<div id="commitList" class="navList"
     data-href="<?= $this->v['prefix'] ?>dcommit/?orig=<?= $this->v['orig'] ?>&dest=<?= $this->v['dest'] ?>"
    >
    <table class="table table-striped table-hover table-responsive">
        <tbody></tbody>
    </table>
</div>


<div id="diffList" class="navList"
     data-href="<?= $this->v['prefix'] ?>diff/?orig=<?= $this->v['orig'] ?>&dest=<?= $this->v['dest'] ?>"
></div>

<script>
    !function($) {
        var nav = $('#compareNav'), loaded = {};
        nav.delegate('a', 'click', function () {
            var href = this.getAttribute('href');
            nav.find('li').removeClass('active');
            this.parentNode.className = 'active';
            $('.navList').hide();
            var node = $(href);
            node.show();
            if (node.data('href') && !loaded[href]) {
                loaded[href] = true;
                $.get(node.data('href'), function(html) {
                    if (node.find('tbody').length) {
                        node.find('tbody').append(html);
                    } else {
                        node.html(html);
                    }
                });
            }
        });

        hapj.conf.set('hook.mergeform', {
            success: function(ret) {
                dialog({
                    content:'添加合并请求成功',
                    title:'操作成功',
                    width:300,
                    okText:'确定',
                    ok: function() {
                        location.href = '<?=$this->v['prefix']?>merge/' + ret.data.merge_id;
                    }
                }).show();
            }
        });
    }(jQuery);

</script>
